[platformio]
src_dir = .

[env:pico2]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#develop
board = rpipico2
framework = arduino
monitor_speed = 115200

build_flags =
    -std=gnu++17

build_src_filter =
    +<src/controller.cpp>
    +<src/estimator.cpp>
    +<firmware/pico_main.cpp>